jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/uacity
  username: root
  password: wapwap12
  maxActive: 3
  maxIdle: 30
  minIdle: 5
  maxWait: 3000
  validationQuery: /* ping */ select 1
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: -1