jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://123.207.120.134:3306/ua_city?useUnicode=yes&characterEncoding=UTF-8
  username: root
  password: wapwap12
  maxActive: 3
  maxIdle: 30
  minIdle: 5
  maxWait: 3000
  validationQuery: /* ping */ select 1
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: -1

spring.velocity.properties.velocimacro.library: /templates/macro.vm
spring.velocity.properties.velocimacro.library.autoreload: true
spring.velocity.charset: UTF-8
spring.velocity.content-type: text/html

spring.http.encoding.charset: UTF-8 # the encoding of HTTP requests/responses
spring.http.encoding.enabled: true # enable http encoding support
spring.http.encoding.force: true

# MULTIPART (MultipartProperties)
multipart.enabled: true
multipart.file-size-threshold: 0 # Threshold after which files will be written to disk.
multipart.location:  # Intermediate location of uploaded files.
multipart.max-file-size: 128Kb # Max file size.
multipart.max-request-size: 128Kb # Max request size.

